### ISSUE TITLE
Declaration

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system-community-backlog#1]
## What
Provide a break/check point before a user submits an application that tells users about any legal or monetary implications on submitting the application or giving incorrect information.

### Example: New Style JSA
<img width="967" alt="Screen Shot 2021-02-11 at 10 22 46" src="https://user-images.githubusercontent.com/57486301/107624662-2001b400-6c53-11eb-873e-c1a6a50170f5.png">

### Example: Pension credit
<img width="803" alt="Screen Shot 2021-02-11 at 10 23 49" src="https://user-images.githubusercontent.com/57486301/107624813-4f182580-6c53-11eb-81d3-7efa12dbcdee.png">

### Example: Budgeting loans
<img width="793" alt="Screen Shot 2021-02-11 at 10 24 08" src="https://user-images.githubusercontent.com/57486301/107624844-57706080-6c53-11eb-81bd-a3492a7ad253.png">

### Example: Apply for NINO
<img width="484" alt="Screen Shot 2021-02-11 at 10 24 53" src="https://user-images.githubusercontent.com/57486301/107624909-70791180-6c53-11eb-8160-34eb2ea46ded.png">

## Why
This pattern appears in most DWP citizen-facing services but lacks consistency (see examples above). A design has previously been published on the old DWP design pattern library.

## Anything else

Currently on the GDS backlog https://github.com/alphagov/govuk-design-system-backlog/issues/29

#### Research

- User type: Citizens
- Accessibility: Tested on JAWS, Dragon, Zoomtext and Read&Write

#### Services

- Check your State Pension

#### When to use

The declaration is the digital equivalent to signing a paper form. You should only use it when you have a rules in your policy that could affect your users legally.

It should also be used if using your service could alter their quality of life. For example, if applying for a benefit might reduce other support they may be receiving.

#### When not to use

You must not use the declaration if your content is not clear. Legal wording should be simplified to remove jargon.

Your declarion should be short and to the point. It should not be used as a catch all method to bypass good content design in the rest of your service.

### Code
<details>
<summary>HTML</summary>

```html
<main id="content" role="main">
  <div class="grid-row">
    <div class="column-two-thirds">
        
      <h1 class="heading-large">Declaration</h1>

      <p class="text">
        By sending the application you agree that:
      </p>

      <ul class="list-bullet">
        <li>the information is correct and complete as far as you know</li>
        <li>you&rsquo;ll pay back any money you&rsquo;re overpaid if you&rsquo;re asked to</li>
      </ul>

      <div class="legal-message">
        <p class="text">
          You could be prosecuted or have to pay a financial penalty if you
          deliberately give the wrong or incomplete information or don&rsquo;t
          report changes.
        </p>
      </div>

      <p>
        <a href="#" class="button">I agree - send my application</a>
      </p>

    </div>
  </div>
</main>
```
</details>
<details>
<summary>CSS</summary>

```CSS
.legal-message {
  background: url(https://assets.digital.cabinet-office.gov.uk/static/icon-important-aab708504574eda2dc4a4de0802be03dbbd70d57b422de93e55e265c9ae2fc43.png) no-repeat scroll 0 0.5em;
  background-image: url(https://assets.digital.cabinet-office.gov.uk/static/icon-important-2x-c948a58b675598f444f7f8fffd9ebf3d740905da332308c65b0dcb4af880d7ba.png);
  background-position: left center;
  background-size: 34px 34px;
  margin: 30px 0;
  min-height: 34px;
  padding-left: 60px;
}     
```
</details>

### Sketch
[sketch.zip](https://github.com/dwp/design-system-community-backlog/files/6164757/sketch.zip)

**Original issue information:** 12 Feb 2018 @abbott567 https://github.com/dwp/design-system-community-backlog/issues/38

## Recommendations
The pattern was taken to the Working Group in January 2021. It was agreed that the pattern was ready to published without the additional radios/check boxes etc that had been included in the iteration.
